# Generated by Django 3.2.9 on 2021-11-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_project_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='time_create',
            field=models.DateField(auto_now=True),
        ),
    ]
