# Generated by Django 3.2.9 on 2021-11-28 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_project_time_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='time_create',
        ),
    ]
